CREATE TABLE EMP_DATA
(
  EMP_ID serial NOT NULL,
  MGR_ID INTEGER,
  YEAR_OF_SERV INTEGER,
  CONSTRAINT pk_emp_data PRIMARY KEY (EMP_ID)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE EMP_DATA
  OWNER TO postgres;